name: CI (dependabot)

on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout project
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: '16'

      - name: Run `npm install`
        run: npm install

      - name: Run `npm run all`
        run: npm run all
