name: CI

on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: "16"

      - name: Run `npm install`
        run: npm install

      - name: Run `npm run all`
        run: npm run all

      - name: Save PR number
        run: echo ${{ github.event.number }} > PR_NUMBER

      - name: Upload artifact with `PR_NUMBER`
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # v3.1.1
        with:
          name: PR_NUMBER
          path: PR_NUMBER

      - name: Upload artifact with `dist` folder
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # v3.1.1
        with:
          name: dist
          path: dist/

      - name: Upload artifact with `covertura.xml`
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # v3.1.1
        with:
          name: cobertura
          path: coverage/cobertura-coverage.xml
