name: CI

on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # v3.5.1
        with:
          node-version: "16"

      - name: Run `npm install`
        run: npm install

      - name: Run `npm run all`
        run: npm run all

      - name: Save PR number
        run: echo ${{ github.event.number }} > PR_NUMBER

      - name: Upload artifact with `PR_NUMBER`
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # v3.1.1
        with:
          name: PR_NUMBER
          path: PR_NUMBER

      - name: Upload artifact with `dist` folder
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # v3.1.1
        with:
          name: dist
          path: dist/
