name: CI

on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - uses: actions/setup-node@04c56d2f954f1e4c69436aa54cfef261a018f458 # v2.5.0
        with:
          node-version: "16"

      - name: Run `npm install`
        run: npm install

      - name: Run `npm run all`
        run: npm run all
