name: CI

on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # v3.5.1
        with:
          node-version: "16"

      - name: Run `npm install`
        run: npm install

      - name: Run `npm run all`
        run: npm run all

      - name: Save PR number to `dist`
        run: echo ${{ github.event.number }} > ./dist/PR_NUMBER

      - name: Upload artifact with `dist` folder
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # v3.1.1
        with:
          name: dist
          path: dist/
