name: Add comment with code-coverage to PR

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  add-comment-with-code-coverage:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'workflow_run' &&
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout project
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Download cobertura.xml file
        uses: dawidd6/action-download-artifact@bd10f381a96414ce2b13a11bfa89902ba7cea07f # v2.24.3
        with:
          run_id: ${{github.event.workflow_run.id }}
          name: cobertura
          path: .

      - name: Download PR_NUMBER
        uses: dawidd6/action-download-artifact@bd10f381a96414ce2b13a11bfa89902ba7cea07f # v2.24.3
        with:
          run_id: ${{github.event.workflow_run.id }}
          name: PR_NUMBER
          path: .

      - name: Extract PR number
        id: extract-pr-number
        run: |
          pr_number=$(cat ./PR_NUMBER)
          echo "PR_NUMBER=$pr_number" >> $GITHUB_OUTPUT

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95 # v1.3.0
        with:
          filename: cobertura-coverage.xml
          badge: true
          format: markdown
          output: both
          thresholds: "60 80"

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@fcf6fe9e4a0409cd9316a5011435be0f3327f1e1 # v2.3.1
        with:
          recreate: true
          header: coverage
          number: ${{ steps.extract-pr-number.outputs.PR_NUMBER }}
          path: code-coverage-results.md
