name: Release a snapshot artifact for a PR

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  release-snapshot-artifact:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'workflow_run' &&
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout project
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      - name: Download dist folder
        uses: dawidd6/action-download-artifact@e6e25ac3a2b93187502a8be1ef9e9603afc34925 # v2.24.2
        with:
          run_id: ${{github.event.workflow_run.id }}
          name: dist
          path: dist

      - name: Download PR_NUMBER
        uses: dawidd6/action-download-artifact@e6e25ac3a2b93187502a8be1ef9e9603afc34925 # v2.24.2
        with:
          run_id: ${{github.event.workflow_run.id }}
          name: PR_NUMBER
          path: .

      - name: Remove `dist` from `.gitignore`
        run: sed -i -E 's|^/?dist/?||g' .gitignore

      - name: Extract PR number
        id: extract-pr-number
        run: |
          pr_number=$(cat ./PR_NUMBER)
          echo "PR_NUMBER=$pr_number" >> $GITHUB_OUTPUT

      - name: Create snapshot branch
        uses: alejandrohdezma/actions/commit-and-push@v1
        with:
          message: "Release snapshot for #${{ steps.extract-pr-number.outputs.PR_NUMBER }}"
          force-push: "true"
          branch: snapshots/${{ steps.extract-pr-number.outputs.PR_NUMBER }}
      
      - name: Create Comment
        uses: marocchino/sticky-pull-request-comment@fcf6fe9e4a0409cd9316a5011435be0f3327f1e1 # v2.3.1
        with:
          recreate: true
          number: ${{ steps.extract-pr-number.outputs.PR_NUMBER }}
          message: |
            A snapshot release has been created as `snapshots/${{ steps.extract-pr-number.outputs.PR_NUMBER }}`.

            You can test it out with:

            ```yaml
            uses: scala-steward-org/scala-steward-action@snapshots/${{ steps.extract-pr-number.outputs.PR_NUMBER }}
            ```

            It will be automatically recreated on any change to this PR.
